version: '3'
services:
  web:
      build: .
      container_name: great
      volumes:
      - .:/code
      - static:/code/static_cdn
      - media:/code/media_cdn
      expose:
        - 8080
      command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 projectname.wsgi -b 0.0.0.0:8080"
  nginx:
      restart: always
      build: nginx/nginx.conf/
      volumes:
        - ./nginx.conf/:/etc/nginx.conf/conf.d
        - static:/code/static_cdn
        - media:/code/media_cdn
      ports:
        - "1221:80"
      links:
        - web
volumes:
  pgdata:
  media:
  static: